"""Add fk to shipment in listing table

Revision ID: 25416b446c1d
Revises: c49865978f9f
Create Date: 2021-02-01 17:34:19.290327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '25416b446c1d'
down_revision = 'c49865978f9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listings', sa.Column('b_shipment_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.add_column('listings', sa.Column('s_shipment_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'listings', 'shipments', ['b_shipment_id'], ['id'])
    op.create_foreign_key(None, 'listings', 'shipments', ['s_shipment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_constraint(None, 'listings', type_='foreignkey')
    op.drop_column('listings', 's_shipment_id')
    op.drop_column('listings', 'b_shipment_id')
    # ### end Alembic commands ###
