"""Create listings table

Revision ID: 67f6e6a7e8f3
Revises: e06d7716b2ba
Create Date: 2021-01-28 18:22:44.617979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '67f6e6a7e8f3'
down_revision = 'e06d7716b2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('game_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('price', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('seller_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('buyer_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listings')
    # ### end Alembic commands ###
