"""Remove listing count from games

Revision ID: 8c1a002a9bdc
Revises: d6d897da7c1e
Create Date: 2021-01-29 10:05:06.689242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c1a002a9bdc'
down_revision = 'd6d897da7c1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'listing_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('listing_count', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
