"""Add foreign keys for listing and seller to shipment table

Revision ID: 9866c9d4ede3
Revises: 25416b446c1d
Create Date: 2021-02-01 21:47:50.413094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9866c9d4ede3'
down_revision = '25416b446c1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('listing_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.add_column('shipments', sa.Column('seller_id', postgresql.UUID(as_uuid=True), nullable=False))
    op.create_foreign_key(None, 'shipments', 'listings', ['listing_id'], ['id'])
    op.create_foreign_key(None, 'shipments', 'users', ['seller_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_constraint(None, 'shipments', type_='foreignkey')
    op.drop_column('shipments', 'seller_id')
    op.drop_column('shipments', 'listing_id')
    # ### end Alembic commands ###
