"""Fix nullability in listings table

Revision ID: be3d73670f91
Revises: e74f82ce23d0
Create Date: 2021-01-29 10:19:03.311525

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'be3d73670f91'
down_revision = 'e74f82ce23d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'buyer_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('listings', 'seller_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listings', 'seller_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('listings', 'buyer_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###
