"""Add shipment table and fk link from listing table

Revision ID: c49865978f9f
Revises: be3d73670f91
Create Date: 2021-02-01 17:32:49.035007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c49865978f9f'
down_revision = 'be3d73670f91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipments',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('label', sa.String(length=1024), nullable=True),
    sa.Column('shipment_type', sa.Enum('SELLER', 'BUYER', name='shipmenttype'), nullable=False),
    sa.Column('from_addr', sa.String(length=1024), nullable=True),
    sa.Column('to_addr', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipments')
    # ### end Alembic commands ###
