"""Add username and password to user table

Revision ID: d6d897da7c1e
Revises: 67f6e6a7e8f3
Create Date: 2021-01-28 21:43:02.052704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d897da7c1e'
down_revision = '67f6e6a7e8f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=1024), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=64), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'username')
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
